// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBqr3nwqJUmTr4n3CvZQFFXdHHJCHUnwqQ',
    appId: '1:215881434456:web:a4ebb1d6f4b6db337a112d',
    messagingSenderId: '215881434456',
    projectId: 'accommediary-a8703',
    authDomain: 'accommediary-a8703.firebaseapp.com',
    storageBucket: 'accommediary-a8703.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHm2k7yVHWaVhzlzTcfYWs6u0hpwySTqg',
    appId: '1:215881434456:android:ec8265a29e7de8dc7a112d',
    messagingSenderId: '215881434456',
    projectId: 'accommediary-a8703',
    storageBucket: 'accommediary-a8703.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtR3jZk9jn51qIoMj8oeVDr-b34aQUZHE',
    appId: '1:215881434456:ios:398624e1277af5257a112d',
    messagingSenderId: '215881434456',
    projectId: 'accommediary-a8703',
    storageBucket: 'accommediary-a8703.firebasestorage.app',
    iosBundleId: 'com.example.accommediary',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCtR3jZk9jn51qIoMj8oeVDr-b34aQUZHE',
    appId: '1:215881434456:ios:398624e1277af5257a112d',
    messagingSenderId: '215881434456',
    projectId: 'accommediary-a8703',
    storageBucket: 'accommediary-a8703.firebasestorage.app',
    iosBundleId: 'com.example.accommediary',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBqr3nwqJUmTr4n3CvZQFFXdHHJCHUnwqQ',
    appId: '1:215881434456:web:215a8454b83283987a112d',
    messagingSenderId: '215881434456',
    projectId: 'accommediary-a8703',
    authDomain: 'accommediary-a8703.firebaseapp.com',
    storageBucket: 'accommediary-a8703.firebasestorage.app',
  );
}
